### PR TITLE
Add download of data bundle for powerd-data

### PR DESCRIPTION
**Pull request by ClaraBuettner**
As soon as we published the small data bundle on zenodo, this branch can be merged. 
It includes the code needed to download and process the data. 
I was able to create the deposit id for the draft already, so no further changes should be needed.

### CODE REVIEW

**Comment by ClaraBuettner** [comment]
Add data for industrial gas demands that is not accessible anymore (see #294)

**Comment by ClaraBuettner** [comment]
The results from a new pypsa-eur run will be also included in the data bundle

**Comment by CarlosEpia** [comment]
The file _district_heating_shares_egon.csv_ is required in [pypsaeur](https://github.com/openego/powerd-data/blob/dev/src/egon/data/datasets/pypsaeur/__init__.py)

**Comment by CarlosEpia** [comment]
The file _egon_demandregio_cts_ind.csv_ is required in [demandregio](https://github.com/openego/powerd-data/blob/6c066f4afa429d0124ab0edb0ac3474143db88fe/src/egon/data/datasets/demandregio/__init__.py#L636)

**Comment by CarlosEpia** [comment]
In addition, some files were added manually to run pypsaeur on the server.

**Comment by ClaraBuettner** [comment]
> The results from a new pypsa-eur run will be also included in the data bundle

Will be added in the next version

**Comment by ClaraBuettner** [comment]
@CarlosEpia: The data is now uploaded so we can merge this PR

**Review by CarlosEpia — APPROVED** [review]
I tested these changes locally and it works correctly.

**Pull request merged**
